project:
  type: book
  output-dir: docs


book:
  title: "Guía Técnica MBHT"
  subtitle: "Para la actualización de la Matriz de Bienestar Humano Territorial 2025–2026"
  author:
    - name: Denis Berroeta González
      url: https://cit.uai.cl/denis-berroeta/
      affiliation: Centro de Inteligencia Territorial
      affiliation-url: https://cit.uai.cl
      email: denis.berroeta@uai.cl
  date: "2025-07-09"
  page-footer:
    left: "Copyright 2025, {{< var cit.name >}}"
  chapters:
    - index.qmd
    - intro.qmd
    # - marco_ref.qmd
    # - met_actualizacion.qmd
    - c_geometric.qmd
    # - proyectos.qmd
    # - recomendaciones.qmd
    # - part: "Marco de Referencia"
      # chapters:
        # - marco_ref.qmd
        # - def_claves.qmd
        # - dim_mbht.qmd
        # - clas_institucionales.qmd
    - references.qmd
    - anexos.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    html-math-method: katex
    css: style.css
    toc: true
    toc-expand: 1
    toc-title: "Contenidos"
    fig-cap-location: "margin"
    tab-cap-location: "bottom"
    fig-align: "center"
    mailto: "denis.berroeta@uai.cl"
    crossref:
      fig-prefix: Figura   # (default is "Figure")
      tbl-prefix: Tabla # (default is "Table")
      eq-prefix: Ecuación 


